package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rampart</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.sub{font-size:.65rem;color:var(--cm)}.main{max-width:700px;margin:0 auto;padding:1rem}.search{width:100%;background:var(--bg2);border:1px solid var(--bg3);color:var(--cream);padding:.4rem .6rem;font-family:var(--mono);font-size:.78rem;margin-bottom:.6rem;outline:none}.search:focus{border-color:var(--rust)}.stats{display:flex;gap:1rem;margin-bottom:.8rem;flex-wrap:wrap}.stat{text-align:center}.stat-n{font-size:1.2rem;color:var(--rl);font-family:var(--serif)}.stat-l{font-size:.55rem;color:var(--cm);text-transform:uppercase;letter-spacing:1px}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.item{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.3rem;cursor:pointer;transition:border-color .15s}.item:hover{border-color:var(--leather)}.item h3{font-size:.82rem;margin-bottom:.15rem}.item-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.5rem;flex-wrap:wrap}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.del{color:var(--cm);cursor:pointer;font-size:.65rem;float:right}.del:hover{color:var(--rust)}</style></head>
<body><div class="hdr"><div><h1><span>Stockyard</span> Rampart</h1><div class="sub">Self-hosted IP blocklist manager</div></div><button class="btn btn-p" onclick="showModal()">+ New</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/rampart/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div class="stats" id="stats"></div>
<input class="search" id="search" placeholder="Search block_rules..." oninput="debounceSearch()">
<div id="list"></div></div>
<div class="modal-bg" id="modal" style="display:none" onclick="if(event.target===this)hideModal()"><div class="modal"><h2 id="mt">New BlockRule</h2>
<label class="fl">Cidr</label><input type="text" id="f-cidr" placeholder="Cidr"><label class="fl">Reason</label><input type="text" id="f-reason" placeholder="Reason"><label class="fl">Source</label><input type="text" id="f-source" placeholder="Source"><label class="fl">Enabled</label><input type="number" id="f-enabled" placeholder="Enabled"><label class="fl">Hit Count</label><input type="number" id="f-hit_count" placeholder="Hit Count"><label class="fl">Expires At</label><input type="text" id="f-expires_at" placeholder="Expires At"><label class="fl">Last Hit At</label><input type="text" id="f-last_hit_at" placeholder="Last Hit At">
<div style="margin-top:1rem;display:flex;gap:.5rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="color:var(--cm);border-color:var(--bg3)" onclick="hideModal()">Cancel</button></div></div></div>
<script>
const API="/api/block_rules";let editId=null,timer=null,curFilter="";

function showModal(id){editId=id||null;document.getElementById("mt").textContent=id?"Edit":"New";if(id){fetch(API+"/"+id).then(r=>r.json()).then(e=>{document.getElementById("f-cidr").value=e.cidr||"";document.getElementById("f-reason").value=e.reason||"";document.getElementById("f-source").value=e.source||"";document.getElementById("f-enabled").value=e.enabled||"";document.getElementById("f-hit_count").value=e.hit_count||"";document.getElementById("f-expires_at").value=e.expires_at||"";document.getElementById("f-last_hit_at").value=e.last_hit_at||"";})}else{document.getElementById("f-cidr").value="";document.getElementById("f-reason").value="";document.getElementById("f-source").value="";document.getElementById("f-enabled").value="";document.getElementById("f-hit_count").value="";document.getElementById("f-expires_at").value="";document.getElementById("f-last_hit_at").value=""}document.getElementById("modal").style.display="flex"}
function hideModal(){document.getElementById("modal").style.display="none";editId=null}
function debounceSearch(){clearTimeout(timer);timer=setTimeout(load,300)}
function filterBy(v){curFilter=v;load()}
async function loadStats(){const r=await fetch("/api/stats");const d=await r.json();const el=document.getElementById("stats");let h='<div class="stat"><div class="stat-n">'+d.total+'</div><div class="stat-l">Total</div></div>';if(d.by_status){for(const[k,v]of Object.entries(d.by_status)){h+='<div class="stat"><div class="stat-n" style="color:'+stc(k)+'">'+v+'</div><div class="stat-l">'+k.replace(/_/g," ")+'</div></div>'}};el.innerHTML=h}
async function load(){let url=API;const q=document.getElementById("search").value;const p=[];if(q)p.push("q="+encodeURIComponent(q));if(curFilter)p.push("status="+curFilter);if(p.length)url+="?"+p.join("&");const r=await fetch(url);const d=await r.json();const items=d.block_rules||[];const el=document.getElementById("list");if(!items.length){el.innerHTML='<div class="empty">No block_rules yet</div>';loadStats();return}
el.innerHTML=items.map(e=>{return '<div class="item" ondblclick="showModal(\''+e.id+'\')"><span class="del" onclick="event.stopPropagation();del(\''+e.id+'\')">x</span><h3>'+e.cidr+'</h3><div class="item-meta"><span>${e.reason||"\u2014"}</span><span>${e.source||"\u2014"}</span><span>${e.enabled||"\u2014"}</span><span>${e.hit_count||"\u2014"}</span></div></div>'}).join("");loadStats()}
async function save(){const body={"cidr":document.getElementById("f-cidr").value,"reason":document.getElementById("f-reason").value,"source":document.getElementById("f-source").value,"enabled":parseInt(document.getElementById("f-enabled").value)||0,"hit_count":parseInt(document.getElementById("f-hit_count").value)||0,"expires_at":document.getElementById("f-expires_at").value,"last_hit_at":document.getElementById("f-last_hit_at").value};const method=editId?"PUT":"POST";const url=editId?API+"/"+editId:API;await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});hideModal();load()}
async function del(id){await fetch(API+"/"+id,{method:"DELETE"});load()}
load();loadStats()
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
